export default function Ex6() {
  return (
   <div className="overflow-auto w-[500px] h-[200px]">
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolore qui, impedit odit in numquam voluptates pariatur quas natus! Illum eligendi sint repudiandae ratione ullam temporibus explicabo impedit cumque nobis voluptatem.
    Impedit omnis fugiat nam ex consequatur unde, commodi deleniti iure, dolores reprehenderit corporis molestias, temporibus laudantium sunt a voluptatem eaque similique neque tempore quos! Corrupti perferendis suscipit voluptate amet iusto.
    Voluptatibus veritatis adipisci vel dignissimos saepe ab sed iure. Consequuntur quod laborum amet molestias odit, assumenda debitis quos animi culpa nihil fuga ullam. Totam porro eligendi blanditiis accusantium, architecto natus?
    Quibusdam ratione, labore quod facere animi delectus. Veniam unde nostrum fugiat porro labore doloremque, laboriosam modi sequi, deserunt laborum excepturi dolorum delectus. Deleniti nesciunt magni ab quae voluptatibus qui nostrum!
    A nisi aliquam sit ex labore recusandae sed quae modi velit? Dolorem ad neque ab, ipsa aliquam dolorum aspernatur consequuntur magni quisquam vel obcaecati quaerat iusto unde, explicabo, quibusdam tempore.
    Placeat, vitae veniam odit eos tempore nihil molestiae provident praesentium et, natus harum ipsum, soluta dolores qui. Laboriosam nobis nihil, ea quia commodi corrupti tenetur consequatur, saepe necessitatibus sequi sunt.
    Itaque odit officiis ipsam, quasi magnam dolorem doloribus dolore eaque. Quod, incidunt! Deleniti molestias dolor ea consequuntur nihil earum incidunt enim ipsa laudantium alias in eos qui, tempore omnis eveniet.
    Libero maiores nisi quae dolor molestias laudantium tenetur amet iure recusandae ratione vero nesciunt in doloremque quos quibusdam vitae itaque magni obcaecati officiis nulla magnam saepe a, aut atque! Aut!
    Tenetur, architecto? Nisi animi, ratione, enim quod molestias dolores minima esse placeat fugit tempore exercitationem modi quisquam soluta nobis, in quis reiciendis sit! Quam illo cumque corrupti magni repellendus cupiditate!
    Animi, harum ipsam eos ad possimus at iste quos sapiente obcaecati dicta minima laudantium quo mollitia commodi odio eum iusto. Nihil iste quo aliquid laboriosam sit sequi facilis distinctio quaerat!
    Laborum possimus minus dignissimos ut in expedita velit modi quo tempore, cumque, eos officia? Libero reprehenderit suscipit architecto optio obcaecati labore quidem sed veritatis cupiditate aperiam doloribus molestiae, voluptates minima.
    Nesciunt numquam dolorum, delectus incidunt tenetur esse nihil deserunt inventore eaque maxime voluptas dolor id ipsam voluptatum, animi quisquam? Voluptate provident beatae, at porro perspiciatis velit libero similique repellendus deserunt?
    Expedita adipisci ipsam, ex impedit eius, tempora rem nam quo quibusdam eveniet voluptatem accusantium quidem optio quia, saepe libero velit beatae provident tenetur a ut. Porro minima eveniet eos veniam.
    Dignissimos placeat tenetur quod sint beatae laborum eius fugit dolores, esse nemo est asperiores odit, nihil unde minima alias! Aut illo dolorum id laboriosam voluptates excepturi possimus veritatis pariatur accusantium?
    Distinctio facilis minus itaque. Tempore aut, dicta ipsam quas quia cupiditate sit laudantium, porro adipisci nihil, aliquid vitae aperiam natus! Totam dolores sapiente saepe suscipit ad reprehenderit doloremque natus libero.
    Laboriosam quo id beatae aliquam suscipit vero aut perspiciatis debitis magnam tempora, eaque quae iste adipisci corrupti, provident tenetur quibusdam? Suscipit architecto earum voluptates quia impedit quidem laborum libero deleniti.
    Accusantium dolorum reprehenderit laudantium veniam ex consequuntur fuga, sunt sapiente, omnis molestias et nulla, minus quaerat quo velit quam maxime nemo! Ea iusto incidunt ipsam accusantium veniam error saepe beatae.
    Quos nostrum corrupti, voluptatibus quam facilis hic ab, maxime ratione recusandae, placeat magnam inventore atque alias dignissimos quas debitis sit est fugiat aspernatur numquam eaque sunt aliquam. Iste, quae expedita?
    Ad provident commodi molestias hic accusamus quas obcaecati ullam aliquid iure tenetur repellat enim minima, architecto aliquam saepe aut. Non deleniti ut ipsa iste omnis. Quis labore non eaque corrupti?
    Repudiandae vitae nisi, repellendus veniam doloremque nobis ex tenetur natus recusandae mollitia pariatur repellat qui magni ab magnam totam reiciendis, iusto perspiciatis iure eaque quae dolorem nesciunt? Odit, assumenda soluta.
    Porro iste molestiae atque vel odio sunt, architecto dolore rem, obcaecati voluptas repellendus labore officiis officia, facere sint libero nobis numquam. Ex nostrum nihil, porro unde maxime minima numquam impedit.
    Necessitatibus laboriosam accusantium veniam totam placeat, consequatur neque eaque perferendis, fuga eius repellat nostrum ad quibusdam id. Enim voluptate fugiat reprehenderit soluta provident a obcaecati earum possimus eos, alias unde!
    Inventore ab ullam eveniet corporis magni quam tempora aliquid dolorem voluptatum laborum? Beatae, quibusdam labore quia libero velit ut excepturi? Quos eligendi animi fugit esse iste aspernatur, consectetur expedita corrupti.
    Provident impedit ratione ab corrupti labore? Optio neque, exercitationem quia ab nihil nisi iusto ut natus ducimus perspiciatis distinctio, odio explicabo. Qui natus accusantium vitae ad, ab repellendus ut omnis.
    Laboriosam magni ipsa totam ullam? Dolorem laborum, alias sint adipisci odio provident fugit quod qui, quae, veritatis ut assumenda? Porro eaque consequatur animi a possimus repudiandae doloremque, minima quam temporibus.
    Dolorum voluptates harum exercitationem! Quasi et voluptates dolorum aliquam quod voluptatibus sit minus quam voluptas adipisci? Reiciendis accusamus aut tempore provident consectetur, odio blanditiis asperiores reprehenderit hic labore cupiditate beatae.
    Vel, deserunt quam ex debitis quisquam eaque dignissimos labore doloremque a culpa enim, aliquid omnis repellendus excepturi quos quibusdam inventore voluptatibus nisi corporis aspernatur eveniet. Veritatis provident harum vel fugit?
    Repellat odit dolore a nisi nostrum sit dignissimos fuga ab nam, repudiandae vitae in alias dolorem quo quibusdam fugiat tempore quae quis id? Accusamus eum aspernatur perspiciatis esse expedita repudiandae.
    Ipsam blanditiis inventore illo modi et rem atque sint fugit? Laudantium eligendi sit nobis quasi nesciunt veniam delectus praesentium, corrupti totam alias pariatur eius dolorem exercitationem aut ut corporis nulla.
    Magni cupiditate ducimus, quo veritatis esse qui ex praesentium aliquam fugiat labore nisi maxime sunt voluptas repudiandae ut accusantium aspernatur. Sit nesciunt earum soluta consequatur quod id dolorum, atque nemo?
    Saepe rem vitae eius fugiat blanditiis dolore voluptate, tenetur architecto amet voluptatem explicabo neque, sunt atque maxime, reiciendis porro expedita! Culpa quas quia, aliquam repellendus rerum recusandae est aliquid? Debitis!
    Ex voluptas atque error quae? Odit quam illo adipisci ducimus. Laboriosam, eum exercitationem! Voluptate dignissimos odit nisi sequi aliquam dolore quidem ratione ipsam libero. Animi porro ipsam recusandae? Voluptatibus, maiores?
    Id corrupti perspiciatis tempore, laboriosam hic adipisci officia totam esse necessitatibus. Sed doloremque officia impedit modi odio maiores quia in magni fugit nisi totam porro, at possimus similique, quisquam expedita?
    At sunt quidem necessitatibus ex aut placeat? Deserunt, recusandae quae molestias inventore ipsum reiciendis ea consectetur explicabo quo magnam quasi, ipsa alias maxime? Hic quia aspernatur molestiae sunt officiis? Expedita.
    Ipsa, est libero. Odio minus nihil distinctio ratione minima eaque, rerum dolores ea veritatis quidem animi consequuntur asperiores neque sed et nisi earum nesciunt quisquam error magni ducimus labore. Voluptatum.
    Repellendus eius iste, maiores quae quibusdam, obcaecati accusamus hic voluptatem quam accusantium consectetur ut nihil cum architecto quasi cumque rerum labore, fugiat autem debitis veritatis unde? Pariatur quis ullam quod?
    Rerum repellat fugit accusantium nesciunt architecto laboriosam sit officia impedit, dolores atque, animi ipsa maiores vel iusto veniam delectus assumenda asperiores ullam mollitia nostrum neque incidunt pariatur! Ea, placeat consectetur?
    Obcaecati dolorum officiis sunt odio ipsa quasi quibusdam quae beatae vero culpa pariatur, magnam ducimus quaerat veniam modi, sapiente asperiores deleniti excepturi natus! Numquam ipsa necessitatibus deserunt illo deleniti magni.
    Sapiente nihil tempore obcaecati nemo modi, quia at sed aperiam fuga autem asperiores hic, provident voluptatum ea cum quis, voluptas consequuntur aut fugiat ipsum maxime? Et unde obcaecati autem impedit?
    Consequuntur, excepturi veniam non libero quas rerum molestiae suscipit laudantium doloribus rem iste harum. Doloremque perferendis esse, error pariatur delectus impedit aliquam ratione. Quo id adipisci porro et! Magnam, veritatis.
    Ducimus, id? Voluptatum architecto totam labore, porro, magni ut delectus voluptatibus quae laborum placeat ea nisi dolorum a. Odit nobis et laboriosam est iusto repellat. Laudantium a asperiores dolorem nulla!
    Praesentium harum nesciunt a. Hic sunt qui nesciunt, itaque numquam explicabo voluptas quam et delectus dolor natus aliquid fugit excepturi sequi asperiores debitis id maiores cumque veritatis nobis maxime perspiciatis?
    Reiciendis nam magnam dicta soluta quam voluptatibus ipsa suscipit voluptatum explicabo debitis nulla, quis id libero magni quas, quod itaque aliquid eos quo temporibus perspiciatis. Nesciunt omnis quisquam ipsam quia.
    Tenetur nam iure doloribus architecto aliquid provident perferendis minus quasi saepe sequi necessitatibus, maiores autem officia labore ad vero, molestiae incidunt magnam ab enim consequuntur. Ipsam dolorem excepturi facere dignissimos!
    Vel possimus unde ab asperiores beatae nam pariatur quod repellat consequuntur culpa reprehenderit cumque, exercitationem deserunt numquam at similique est reiciendis. Sequi tempora suscipit ratione impedit, ipsam eveniet culpa distinctio!
    Natus facere aperiam iusto maiores suscipit, odit molestias adipisci vitae perspiciatis voluptates eius fuga, architecto ex unde dolor autem repellat impedit mollitia in quae voluptatem quaerat soluta culpa veritatis. Magnam.
    Laboriosam earum quam incidunt commodi harum a rem est amet error accusantium, cumque eos! Repudiandae quo mollitia molestiae eligendi accusantium. Aut facilis consectetur quos optio ducimus itaque explicabo. Explicabo, minus?
    Excepturi officiis laborum sapiente vel quibusdam commodi, sequi est explicabo? Sequi, nemo iste, et aspernatur sunt voluptatibus facere eos eligendi adipisci quaerat cumque! Laudantium quisquam eius beatae aliquam. Hic, modi!
    Possimus suscipit debitis sequi eos quo sit asperiores voluptates id consequatur est, quidem nesciunt, atque similique officia illo fugiat quibusdam unde numquam. Qui, minus illum iure aspernatur consectetur saepe corrupti!
    Iste cum sit accusamus porro est at fuga cumque fugiat vitae eveniet, consectetur voluptatem sed quas repellat magni quis recusandae incidunt modi illum officiis itaque? Eaque debitis hic vel expedita.
</div>
  )
}
